In [1]:
import torch 
import numpy 

In [2]:
x = torch.empty(5,3) 
print(x) 
print(x.dtype) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.float32


In [3]:
x1 = numpy.empty([2,4]) 
x1 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [4]:
x1 = numpy.empty([2,4]) 
print(x1)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [6]:
x1 = torch.empty(3) 
x1

tensor([0., 0., 0.])

In [7]:
x1= numpy.empty(3) 
x1

array([0. , 0.5, 1. ])

In [8]:
x1 = numpy.empty([2,3],dtype = int) 
x1 

array([[0, 0, 0],
       [0, 0, 0]])

In [9]:
x = torch.rand(5,3) 
print(x) 
x = torch.randn(5,3) 
print(x) 

tensor([[0.7660, 0.3076, 0.1327],
        [0.2842, 0.2798, 0.6589],
        [0.5898, 0.6996, 0.4821],
        [0.5524, 0.7711, 0.2866],
        [0.2891, 0.9351, 0.6797]])
tensor([[ 0.1064,  0.0742,  1.5871],
        [ 1.2500, -0.6738,  1.5583],
        [ 0.9563, -0.8453, -0.4887],
        [ 1.1050, -0.1968,  0.2554],
        [ 0.9096, -0.1784,  0.7082]])


In [10]:
x = torch.rand_like(x) 
x 

tensor([[0.1349, 0.9520, 0.1206],
        [0.0569, 0.3013, 0.8501],
        [0.5293, 0.5910, 0.0219],
        [0.6971, 0.5034, 0.8475],
        [0.0920, 0.5813, 0.0532]])

In [11]:
x = torch.rand_like(x,dtype=torch.float64) 
x 

tensor([[0.8577, 0.6833, 0.6358],
        [0.3498, 0.4113, 0.9174],
        [0.0648, 0.2811, 0.4291],
        [0.7143, 0.0501, 0.9863],
        [0.6696, 0.4248, 0.8478]], dtype=torch.float64)

In [12]:
x = torch.randn_like(x) 
x 

tensor([[ 0.5706, -0.5083, -0.4307],
        [ 0.2106, -2.4614, -0.2362],
        [ 0.7196, -0.3968,  1.5853],
        [ 0.8170, -1.8088,  0.4909],
        [ 0.5968,  0.0445, -0.1036]], dtype=torch.float64)

In [13]:
x = torch.tensor([2,4],dtype=torch.float) 
print(x) 
x = torch.rand_like(x) 
print(x) 

tensor([2., 4.])
tensor([0.9630, 0.2439])


In [14]:
x = x.new_ones(5,3,dtype=torch.float64) 
x 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [15]:
y = torch.tensor([2,3]) 
print(y) 

tensor([2, 3])


In [16]:
x = torch.Tensor(2,3) 
x 
# 此处的Tensor的T是大写，随机输出一个（2，3）维度的tensor 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [17]:
b = torch.tensor([4,5,6]) 
print(b) 
print(b.dtype) 
b = b.float() 
print(b) 
print(b.dtype) 

tensor([4, 5, 6])
torch.int64
tensor([4., 5., 6.])
torch.float32


In [18]:
x = torch.empty(5,3) 
print(x) 
print(x.size()) 
print(x.shape) 
x = numpy.ones(2) 
print(x.shape) 

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
torch.Size([5, 3])
torch.Size([5, 3])
(2,)


In [19]:
x = torch.arange(1,2,0.1) 
print(x) 
x = torch.linspace(1,2,10) 
print(x) 
# 对比一下arange和linspace的区别 

tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000])
tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])


In [20]:
x = torch.rand(5,3)
y = torch.randn(5,3) 
print(x) 
print(y) 
print(x + y) 
print(torch.add(x,y)) 

tensor([[0.8498, 0.5070, 0.9597],
        [0.8003, 0.3871, 0.5863],
        [0.3995, 0.9820, 0.9935],
        [0.8444, 0.7338, 0.9828],
        [0.5326, 0.7605, 0.3589]])
tensor([[ 0.5783, -1.6492, -0.8064],
        [ 0.3306, -0.0244,  1.9057],
        [ 0.4112,  0.7051,  1.0436],
        [-0.3786,  0.3802, -1.2445],
        [ 0.4391,  1.1666,  0.6033]])
tensor([[ 1.4281, -1.1422,  0.1533],
        [ 1.1309,  0.3627,  2.4920],
        [ 0.8107,  1.6871,  2.0371],
        [ 0.4658,  1.1140, -0.2617],
        [ 0.9718,  1.9270,  0.9622]])
tensor([[ 1.4281, -1.1422,  0.1533],
        [ 1.1309,  0.3627,  2.4920],
        [ 0.8107,  1.6871,  2.0371],
        [ 0.4658,  1.1140, -0.2617],
        [ 0.9718,  1.9270,  0.9622]])


In [21]:
result = torch.empty(5,3) 
torch.add(x,y,out=result) 
print(result)

tensor([[ 1.4281, -1.1422,  0.1533],
        [ 1.1309,  0.3627,  2.4920],
        [ 0.8107,  1.6871,  2.0371],
        [ 0.4658,  1.1140, -0.2617],
        [ 0.9718,  1.9270,  0.9622]])


In [22]:
print(y.add_(x)) 
# add x to y 
# inplace版本的函数 

tensor([[ 1.4281, -1.1422,  0.1533],
        [ 1.1309,  0.3627,  2.4920],
        [ 0.8107,  1.6871,  2.0371],
        [ 0.4658,  1.1140, -0.2617],
        [ 0.9718,  1.9270,  0.9622]])


In [23]:
print(x) 

tensor([[0.8498, 0.5070, 0.9597],
        [0.8003, 0.3871, 0.5863],
        [0.3995, 0.9820, 0.9935],
        [0.8444, 0.7338, 0.9828],
        [0.5326, 0.7605, 0.3589]])


In [24]:
y = x[0,:] #切出了x的第[0]行，即第1行 
print(y) 
y = x[:,0] #切出了x的第[0]列，即第1列 
print(y) 
y = x[:,2] #切出了x的第[2]列，即第3列 
print(y) 

tensor([0.8498, 0.5070, 0.9597])
tensor([0.8498, 0.8003, 0.3995, 0.8444, 0.5326])
tensor([0.9597, 0.5863, 0.9935, 0.9828, 0.3589])


In [25]:
x = torch.rand(5,3,dtype=torch.float) 
x

tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])

In [26]:
print(x[0:2]) #切出第[0]行到第[2]行的前一行，含头不含尾 
print(x[0:5:2]) #从第[0]行到第[5]行，每2行取第1行 
print(x[2:]) #从第[2]行开始取到最后 
print(x[:2]) #从第[0]行开始取，取到第[2]行的前一行，依然是含头不含尾 
print(x[2:-1])

tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802]])
tensor([[0.6476, 0.9160, 0.9386],
        [0.3609, 0.2088, 0.0096],
        [0.7400, 0.7625, 0.9436]])
tensor([[0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])
tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802]])
tensor([[0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355]])


In [27]:
#负数索引，从后往前数，且为从-1开始数
print(x)
print(x[-2:]) # 没有接收列就默认是全部列
print(x[:-2]) 
print(x[:-3]) 

tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])
tensor([[0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])
tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096]])
tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802]])


In [28]:
print(x[0]) 
print(x[:,0]) 
print(x[0,1]) 
print(x[0][1]) 

tensor([0.6476, 0.9160, 0.9386])
tensor([0.6476, 0.5139, 0.3609, 0.8700, 0.7400])
tensor(0.9160)
tensor(0.9160)


In [29]:
print(x) 
r = [1,2,3]  
print(x[r]) 
c = [0,1,2] 
y = x[r,c] 
print(y)  
#r是行索引，c是列索引 
#取出(1,0),(2,1),(3,2)三个位置的值 

tensor([[0.6476, 0.9160, 0.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])
tensor([[0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355]])
tensor([0.5139, 0.2088, 0.9355])


In [30]:
y = x[0,:] 
print(y) 
y += 1 
print(y) 
print(x) 

tensor([0.6476, 0.9160, 0.9386])
tensor([1.6476, 1.9160, 1.9386])
tensor([[1.6476, 1.9160, 1.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [0.8700, 0.1508, 0.9355],
        [0.7400, 0.7625, 0.9436]])


In [31]:
y = x[-2:] 
y += 1 
print(x) 
print(y) 

tensor([[1.6476, 1.9160, 1.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [1.8700, 1.1508, 1.9355],
        [1.7400, 1.7625, 1.9436]])
tensor([[1.8700, 1.1508, 1.9355],
        [1.7400, 1.7625, 1.9436]])


In [32]:
indices = torch.LongTensor([0,2]) # Long
print(indices) 
print(indices.dtype) 
z = torch.index_select(x,0,indices) # 从 x 里按 indices 指定的行号取出行，存到 z
print(z) 
z = torch.index_select(x,1,indices) 
print(z) 
z += 1 
print(x) 
print(z) 
#0指行，1指列 

tensor([0, 2])
torch.int64
tensor([[1.6476, 1.9160, 1.9386],
        [0.3609, 0.2088, 0.0096]])
tensor([[1.6476, 1.9386],
        [0.5139, 0.4802],
        [0.3609, 0.0096],
        [1.8700, 1.9355],
        [1.7400, 1.9436]])
tensor([[1.6476, 1.9160, 1.9386],
        [0.5139, 0.1801, 0.4802],
        [0.3609, 0.2088, 0.0096],
        [1.8700, 1.1508, 1.9355],
        [1.7400, 1.7625, 1.9436]])
tensor([[2.6476, 2.9386],
        [1.5139, 1.4802],
        [1.3609, 1.0096],
        [2.8700, 2.9355],
        [2.7400, 2.9436]])


In [34]:
x = torch.randn(5,3,dtype=torch.float)
print(x) 
mask = x.ge(0.5) # 对 x 里每个元素判断是否大于等于 0.5，返回一个同形状的布尔 tensor
print(mask) 
print(torch.masked_select(x,mask))
# masked_select 按布尔 tensor 取值，等价于 x[mask]
y = x[x>0.5] 
print(y == x[mask])
y += 1 
print(y)
#张量 mask须跟input张量有相同数量的元素数目，但形状或维度不需要相同。 
#注意： 返回的张量不与原始张量共享内存空间。

tensor([[ 0.0081,  1.5644,  1.0292],
        [-0.4869,  0.9917, -1.8184],
        [ 0.2256, -0.4599,  1.3154],
        [-0.6011,  1.5446,  0.6919],
        [-1.7471, -0.1815,  0.3457]])
tensor([[False,  True,  True],
        [False,  True, False],
        [False, False,  True],
        [False,  True,  True],
        [False, False, False]])
tensor([1.5644, 1.0292, 0.9917, 1.3154, 1.5446, 0.6919])
tensor([True, True, True, True, True, True])
tensor([2.5644, 2.0292, 1.9917, 2.3154, 2.5446, 1.6919])


In [35]:
print(x) 
y = x.view(15)  # view 是 PyTorch 的重塑形状，和 NumPy 的 reshape 一样
z = x.view(-1,5) 
print(y) 
print(z) 
print(y.shape,z.shape) 
print(x) 
x += 1 
print(x) 
print(y) 
y += 1 
print(x) 
print(y) 
#view()返回的新tensor和源tensor共享内存 
#列顺序

tensor([[ 0.0081,  1.5644,  1.0292],
        [-0.4869,  0.9917, -1.8184],
        [ 0.2256, -0.4599,  1.3154],
        [-0.6011,  1.5446,  0.6919],
        [-1.7471, -0.1815,  0.3457]])
tensor([ 0.0081,  1.5644,  1.0292, -0.4869,  0.9917, -1.8184,  0.2256, -0.4599,
         1.3154, -0.6011,  1.5446,  0.6919, -1.7471, -0.1815,  0.3457])
tensor([[ 0.0081,  1.5644,  1.0292, -0.4869,  0.9917],
        [-1.8184,  0.2256, -0.4599,  1.3154, -0.6011],
        [ 1.5446,  0.6919, -1.7471, -0.1815,  0.3457]])
torch.Size([15]) torch.Size([3, 5])
tensor([[ 0.0081,  1.5644,  1.0292],
        [-0.4869,  0.9917, -1.8184],
        [ 0.2256, -0.4599,  1.3154],
        [-0.6011,  1.5446,  0.6919],
        [-1.7471, -0.1815,  0.3457]])
tensor([[ 1.0081,  2.5644,  2.0292],
        [ 0.5131,  1.9917, -0.8184],
        [ 1.2256,  0.5401,  2.3154],
        [ 0.3989,  2.5446,  1.6919],
        [-0.7471,  0.8185,  1.3457]])
tensor([ 1.0081,  2.5644,  2.0292,  0.5131,  1.9917, -0.8184,  1.2256,  0.5401,
        

In [36]:
x = torch.randn(4,6) 
print(x) 
y = x.view(-1,2) 
print(y) 
y = x.view(4,-1) 
print(y) 
y = x.view(3,8) 
print(y) 
# -1表示对该维的数目不做限制

tensor([[-0.1595, -0.0846, -0.9256, -0.2117, -2.2403,  0.6316],
        [-0.6513,  0.0291, -1.4553,  0.1813,  0.3151,  1.2254],
        [-0.5001,  0.2796, -0.6866,  1.3009,  1.6897, -0.4926],
        [ 2.1423,  0.3211, -1.6828,  0.7460, -1.4062, -0.7698]])
tensor([[-0.1595, -0.0846],
        [-0.9256, -0.2117],
        [-2.2403,  0.6316],
        [-0.6513,  0.0291],
        [-1.4553,  0.1813],
        [ 0.3151,  1.2254],
        [-0.5001,  0.2796],
        [-0.6866,  1.3009],
        [ 1.6897, -0.4926],
        [ 2.1423,  0.3211],
        [-1.6828,  0.7460],
        [-1.4062, -0.7698]])
tensor([[-0.1595, -0.0846, -0.9256, -0.2117, -2.2403,  0.6316],
        [-0.6513,  0.0291, -1.4553,  0.1813,  0.3151,  1.2254],
        [-0.5001,  0.2796, -0.6866,  1.3009,  1.6897, -0.4926],
        [ 2.1423,  0.3211, -1.6828,  0.7460, -1.4062, -0.7698]])
tensor([[-0.1595, -0.0846, -0.9256, -0.2117, -2.2403,  0.6316, -0.6513,  0.0291],
        [-1.4553,  0.1813,  0.3151,  1.2254, -0.5001,  0.2796, -0.6

In [43]:
x = torch.randn([3, 5])
x_cp = x.clone().view(15)
print(x_cp)
x += 1 
print(x) 
print(x_cp) 
x_cp += 3 
print(x) 
print(x_cp) 
#克隆后的不共享内存

tensor([-0.4022,  0.4565,  0.4954, -0.7517,  0.6107,  0.4858,  0.9079,  0.9732,
         0.4555, -1.0767,  1.6808,  0.3759,  1.2511,  0.0532, -2.1134])
tensor([[ 0.5978,  1.4565,  1.4954,  0.2483,  1.6107],
        [ 1.4858,  1.9079,  1.9732,  1.4555, -0.0767],
        [ 2.6808,  1.3759,  2.2511,  1.0532, -1.1134]])
tensor([-0.4022,  0.4565,  0.4954, -0.7517,  0.6107,  0.4858,  0.9079,  0.9732,
         0.4555, -1.0767,  1.6808,  0.3759,  1.2511,  0.0532, -2.1134])
tensor([[ 0.5978,  1.4565,  1.4954,  0.2483,  1.6107],
        [ 1.4858,  1.9079,  1.9732,  1.4555, -0.0767],
        [ 2.6808,  1.3759,  2.2511,  1.0532, -1.1134]])
tensor([2.5978, 3.4565, 3.4954, 2.2483, 3.6107, 3.4858, 3.9079, 3.9732, 3.4555,
        1.9233, 4.6808, 3.3759, 4.2511, 3.0532, 0.8866])


In [44]:
x = torch.arange(1,3) 
print(x) 
print(x.size()) 
x = torch.arange(1,3).view(1,2) 
print(x) 
print(x.size()) 
# unsqueeze 拓展维数

tensor([1, 2])
torch.Size([2])
tensor([[1, 2]])
torch.Size([1, 2])


In [45]:
x = torch.arange(1,3).view(1,2) 
y = torch.arange(1,4).view(3,1) 
print(y) 
print(x + y) 
# 广播机制的语法规则，两个多维 

tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [46]:
x = torch.tensor([1,2]) 
y = torch.tensor([3,4]) 
id_before = id(y) # id 返回对象的内存地址
y = y + x 
print(id(y) == id_before) 
print(id(y)) 
print(id_before) 

False
6069136960
6068993824


In [47]:
x = torch.tensor([1,2]) 
y = torch.tensor([3,4]) 
id_before = id(y) 
y[:] = y + x 
print(id(y) == id_before) 
print(id(y)) 
print(id_before)

True
6068990384
6068990384


In [48]:
x = torch.tensor([1,2])
y = torch.tensor([3,4]) 
id_before = id(y) 
torch.add(x,y,out=y) #或y += x和y.add_(x) 
print(id(y) == id_before) 

True


In [49]:
#Tensor转Numpy，共享内存 
a = torch.ones(5) 
print(a) 
b = a.numpy() 
print(a,b) 
a += 1 
print(a,b) 
b += 1 
print(a,b) 

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [50]:
#Numpy转Tensor，共享内存 
a = numpy.ones(5) 
b = torch.from_numpy(a) 
print(a,b) 
a += 1 
print(a,b) 
b += 1 
print(a,b) 

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [51]:
c = torch.tensor(a) 
a += 1 
print(a,c) 
#这种办法不共享内存 

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [52]:
from time import time 
a = torch.ones(1000) 
b = torch.ones(1000) 
start = time() 
c = torch.zeros(1000) 
for i in range(1000): 
    c[i] = a[i] + b[i]
print(time() - start) 
# 解释性语言和编译性语言 
# python的加速 

0.0056378841400146484


In [53]:
start = time() 
d = a + b 
print(time() - start)

0.0002791881561279297
