In [3]:
import torch
import numpy as np

In [4]:
tensor = torch.rand(5, 8)
print(tensor)
# 索引第2至3行
rows = tensor[1:3, :] #Python的索引从0开始，所以第2至3行是索引1:3
print(rows)
# 索引奇数列
odd = tensor[:, 1::2]
print(odd)
# 索引所有>0.6的元素
elements = tensor[tensor > 0.6]
print(elements)

tensor([[7.6875e-01, 6.2187e-01, 1.9782e-01, 4.8239e-01, 4.3310e-01, 6.3007e-01,
         9.0182e-03, 3.5076e-01],
        [9.3192e-01, 5.2542e-01, 5.9500e-01, 4.7453e-01, 4.2289e-01, 5.1276e-01,
         1.9436e-01, 8.4139e-01],
        [8.1164e-01, 9.6832e-01, 9.2130e-01, 7.8007e-01, 2.2068e-02, 9.7697e-01,
         4.5217e-01, 4.6672e-01],
        [1.3191e-01, 7.8761e-01, 1.7754e-01, 3.6788e-01, 3.9839e-01, 5.7352e-01,
         4.2082e-01, 7.0767e-01],
        [8.2665e-01, 1.2855e-01, 8.5735e-01, 9.0569e-04, 1.5339e-01, 5.5964e-01,
         6.8846e-01, 2.1758e-01]])
tensor([[0.9319, 0.5254, 0.5950, 0.4745, 0.4229, 0.5128, 0.1944, 0.8414],
        [0.8116, 0.9683, 0.9213, 0.7801, 0.0221, 0.9770, 0.4522, 0.4667]])
tensor([[6.2187e-01, 4.8239e-01, 6.3007e-01, 3.5076e-01],
        [5.2542e-01, 4.7453e-01, 5.1276e-01, 8.4139e-01],
        [9.6832e-01, 7.8007e-01, 9.7697e-01, 4.6672e-01],
        [7.8761e-01, 3.6788e-01, 5.7352e-01, 7.0767e-01],
        [1.2855e-01, 9.0569e-04, 5.5964e-01

In [5]:
x = torch.rand(1, 5)
print(x)
y = torch.rand(6, 1)
print(y)
# 按照广播机制相加
s = x + y
print(s)
t = x.expand(6, 5) + y.expand(6, 5) #需要x和y的形状相同，因此需要扩展为6*5
print(t)
# 将广播相加的结果赋值给x
x = t
print(x)

tensor([[0.1145, 0.6983, 0.4345, 0.1002, 0.6191]])
tensor([[0.7731],
        [0.9973],
        [0.4756],
        [0.8199],
        [0.4530],
        [0.3086]])
tensor([[0.8876, 1.4714, 1.2076, 0.8734, 1.3922],
        [1.1118, 1.6956, 1.4318, 1.0975, 1.6164],
        [0.5901, 1.1738, 0.9101, 0.5758, 1.0947],
        [0.9344, 1.5182, 1.2544, 0.9201, 1.4390],
        [0.5675, 1.1513, 0.8875, 0.5532, 1.0721],
        [0.4230, 1.0068, 0.7430, 0.4088, 0.9276]])
tensor([[0.8876, 1.4714, 1.2076, 0.8734, 1.3922],
        [1.1118, 1.6956, 1.4318, 1.0975, 1.6164],
        [0.5901, 1.1738, 0.9101, 0.5758, 1.0947],
        [0.9344, 1.5182, 1.2544, 0.9201, 1.4390],
        [0.5675, 1.1513, 0.8875, 0.5532, 1.0721],
        [0.4230, 1.0068, 0.7430, 0.4088, 0.9276]])
tensor([[0.8876, 1.4714, 1.2076, 0.8734, 1.3922],
        [1.1118, 1.6956, 1.4318, 1.0975, 1.6164],
        [0.5901, 1.1738, 0.9101, 0.5758, 1.0947],
        [0.9344, 1.5182, 1.2544, 0.9201, 1.4390],
        [0.5675, 1.1513, 0.8875, 0.553

In [6]:
a1 = torch.rand(8, 8)
b1 = torch.rand(8, 8)
print(a1)
print(b1)
# 将张量转化为numpy的array
a2 = a1.numpy()
b2 = b1.numpy()
print(a2)
print(b2)
# 做矩阵相乘
result1 = np.dot(a2, b2)
print(result1)
# 将结果转化为pytorch下的张量类型
result2 = torch.from_numpy(result1)
print(result2)

tensor([[0.4303, 0.2530, 0.3558, 0.9162, 0.1621, 0.0038, 0.5375, 0.7063],
        [0.5080, 0.8842, 0.0623, 0.4533, 0.6568, 0.6790, 0.6777, 0.2427],
        [0.6854, 0.2603, 0.8067, 0.4940, 0.3307, 0.2434, 0.3686, 0.6528],
        [0.3554, 0.9395, 0.8246, 0.9684, 0.0201, 0.2963, 0.2315, 0.5218],
        [0.1315, 0.4302, 0.6447, 0.7672, 0.0810, 0.1533, 0.1201, 0.1420],
        [0.3098, 0.7205, 0.2868, 0.5313, 0.1435, 0.1906, 0.5687, 0.0591],
        [0.1486, 0.1086, 0.6129, 0.3810, 0.0805, 0.2963, 0.3291, 0.4481],
        [0.5743, 0.2961, 0.7895, 0.3004, 0.7922, 0.6591, 0.3941, 0.0018]])
tensor([[0.3033, 0.9441, 0.6075, 0.0282, 0.0845, 0.6154, 0.3461, 0.1514],
        [0.2204, 0.3135, 0.1216, 0.3536, 0.9516, 0.5247, 0.8298, 0.0281],
        [0.3658, 0.4496, 0.4484, 0.2692, 0.9831, 0.8017, 0.0711, 0.9896],
        [0.4673, 0.1354, 0.7953, 0.4845, 0.9413, 0.0427, 0.3287, 0.8437],
        [0.9414, 0.2949, 0.2962, 0.7514, 0.7981, 0.2118, 0.3799, 0.4906],
        [0.5925, 0.7080, 0.7703, 0.15