In [2]:
import torch 
import numpy 

In [3]:
x = torch.empty(5,3) 
print(x) 
print(x.dtype) 

tensor([[1.8576e+27, 1.5737e-42, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00]])
torch.float32


In [4]:
x1 = numpy.empty([2,4]) 
x1 

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        3.44897483e-307],
       [9.45763340e-308, 1.42419938e-306, 7.56603881e-307,
        0.00000000e+000]])

In [5]:
x1 = numpy.empty([2,4]) 
print(x1)

[[6.23042070e-307 4.67296746e-307 1.69121096e-306 3.44897483e-307]
 [9.45763340e-308 1.42419938e-306 7.56603881e-307 0.00000000e+000]]


In [6]:
x1 = numpy.empty(2,4) 

TypeError: Cannot interpret '4' as a data type

In [7]:
x1 = torch.empty(3) 
x1

tensor([0., 0., 0.])

In [8]:
x1= numpy.empty(3) 
x1

array([6.95211369e-310, 2.12199579e-314, 0.00000000e+000])

In [9]:
x1 = numpy.empty([2,3],dtype = int) 
x1 

array([[25895968444448860, 23925768161198147, 32370111954616435],
       [22236802338521180, 13792815030272089, 14637132587794432]])

In [10]:
x = torch.rand(5,3) 
print(x) 
x = torch.randn(5,3) 
print(x) 

tensor([[0.0719, 0.8972, 0.9169],
        [0.7251, 0.9492, 0.3288],
        [0.5861, 0.0088, 0.8293],
        [0.0308, 0.3402, 0.1976],
        [0.5490, 0.3973, 0.1819]])
tensor([[ 0.6366, -0.8856, -2.2269],
        [ 1.0281,  1.2542, -0.1394],
        [ 2.3263,  0.3461, -0.4569],
        [ 1.1929, -1.0634,  0.2339],
        [-1.8206, -0.9216, -0.8458]])


In [11]:
x = torch.rand_like(x) 
x 

tensor([[0.8554, 0.2772, 0.9837],
        [0.4116, 0.4186, 0.1293],
        [0.6743, 0.9880, 0.7061],
        [0.5934, 0.0806, 0.4714],
        [0.0030, 0.8173, 0.5786]])

In [12]:
x = torch.rand_like(x,dtype=torch.float64) 
x 

tensor([[0.6412, 0.5639, 0.9465],
        [0.0650, 0.0094, 0.5996],
        [0.8444, 0.7724, 0.0274],
        [0.7212, 0.9984, 0.6485],
        [0.1180, 0.2870, 0.7741]], dtype=torch.float64)

In [13]:
x = torch.randn_like(x) 
x 

tensor([[ 1.8098, -0.8955, -0.4674],
        [ 0.5314,  1.5552, -1.5187],
        [ 0.8307, -0.0203, -0.6026],
        [-0.1799,  0.3211, -0.6248],
        [-0.8410,  0.3388, -0.3773]], dtype=torch.float64)

In [14]:
x = torch.tensor([2,4],dtype=torch.float) 
print(x) 
x = torch.rand_like(x) 
print(x) 

tensor([2., 4.])
tensor([0.0766, 0.7321])


In [15]:
x = x.new_ones(5,3,dtype=torch.float64) 
x 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [16]:
y = torch.tensor([2,3]) 
print(y) 

tensor([2, 3])


In [17]:
x = torch.Tensor(2,3) 
x 
# 此处的Tensor的T是大写，随机输出一个（2，3）维度的tensor 

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [18]:
b = torch.tensor([4,5,6]) 
print(b) 
print(b.dtype) 
b = b.float() 
print(b) 
print(b.dtype) 

tensor([4, 5, 6])
torch.int64
tensor([4., 5., 6.])
torch.float32


In [19]:
x = torch.empty(5,3) 
print(x) 
print(x.size()) 
print(x.shape) 
x = numpy.ones(2) 
print(x.shape) 

tensor([[ 1.8581e+27,  1.5737e-42, -4.4694e+01],
        [ 1.8489e+00, -3.6977e-20,  1.7337e+00],
        [ 4.5955e+15,  1.7578e+00, -3.5902e-31],
        [ 1.9444e+00,  5.1516e-11,  1.9398e+00],
        [ 8.0927e+12,  1.8327e+00, -7.1316e+18]])
torch.Size([5, 3])
torch.Size([5, 3])
(2,)


In [20]:
x = torch.arange(1,2,0.1) 
print(x) 
x = torch.linspace(1,2,10) 
print(x) 
# 对比一下arange和linspace的区别 

tensor([1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000, 1.8000,
        1.9000])
tensor([1.0000, 1.1111, 1.2222, 1.3333, 1.4444, 1.5556, 1.6667, 1.7778, 1.8889,
        2.0000])


In [21]:
 x = torch.rand(5,3) 
y = torch.randn(5,3) 
print(x) 
print(y) 
print(x + y) 
print(torch.add(x,y)) 

tensor([[0.2431, 0.4658, 0.1252],
        [0.9746, 0.4457, 0.5023],
        [0.3205, 0.2271, 0.9821],
        [0.2930, 0.2308, 0.6961],
        [0.5867, 0.5789, 0.0196]])
tensor([[ 0.2290, -1.1791,  0.8090],
        [ 0.0582,  0.6817,  1.0554],
        [ 2.3176,  0.5050, -0.5048],
        [-0.2480, -0.5191,  0.4103],
        [ 0.0419,  1.9768, -0.0465]])
tensor([[ 0.4722, -0.7133,  0.9341],
        [ 1.0327,  1.1274,  1.5577],
        [ 2.6381,  0.7321,  0.4773],
        [ 0.0450, -0.2883,  1.1064],
        [ 0.6286,  2.5557, -0.0269]])
tensor([[ 0.4722, -0.7133,  0.9341],
        [ 1.0327,  1.1274,  1.5577],
        [ 2.6381,  0.7321,  0.4773],
        [ 0.0450, -0.2883,  1.1064],
        [ 0.6286,  2.5557, -0.0269]])


In [22]:
result = torch.empty(5,3) 
torch.add(x,y,out=result) 
print(result)

tensor([[ 0.4722, -0.7133,  0.9341],
        [ 1.0327,  1.1274,  1.5577],
        [ 2.6381,  0.7321,  0.4773],
        [ 0.0450, -0.2883,  1.1064],
        [ 0.6286,  2.5557, -0.0269]])


In [23]:
print(y.add_(x)) 
# add x to y 
# inplace版本的函数 

tensor([[ 0.4722, -0.7133,  0.9341],
        [ 1.0327,  1.1274,  1.5577],
        [ 2.6381,  0.7321,  0.4773],
        [ 0.0450, -0.2883,  1.1064],
        [ 0.6286,  2.5557, -0.0269]])


In [24]:
print(x) 

tensor([[0.2431, 0.4658, 0.1252],
        [0.9746, 0.4457, 0.5023],
        [0.3205, 0.2271, 0.9821],
        [0.2930, 0.2308, 0.6961],
        [0.5867, 0.5789, 0.0196]])


In [25]:
y = x[0,:] #切出了x的第[0]行，即第1行 
print(y) 
y = x[:,0] #切出了x的第[0]列，即第1列 
print(y) 
y = x[:,2] #切出了x的第[2]列，即第3列 
print(y) 

tensor([0.2431, 0.4658, 0.1252])
tensor([0.2431, 0.9746, 0.3205, 0.2930, 0.5867])
tensor([0.1252, 0.5023, 0.9821, 0.6961, 0.0196])


In [26]:
x = torch.rand(5,3,dtype=torch.float) 
x 

tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665],
        [0.9578, 0.0369, 0.6091]])

In [27]:
print(x[0:2]) #切出第[0]行到第[2]行的前一行，含头不含尾 
print(x[0:5:2]) #从第[0]行到第[5]行，每2行取第1行 
print(x[2:]) #从第[2]行开始取到最后 
print(x[:2]) #从第[0]行开始取，取到第[2]行的前一行，依然是含头不含尾 
print(x[2:-1])

tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843]])
tensor([[0.6994, 0.1726, 0.3281],
        [0.1526, 0.5134, 0.4883],
        [0.9578, 0.0369, 0.6091]])
tensor([[0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665],
        [0.9578, 0.0369, 0.6091]])
tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843]])
tensor([[0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665]])


In [28]:
#负数索引，从后往前数，且为从-1开始数 
print(x[-2:]) 
print(x[:-2]) 
print(x[:-3]) 

tensor([[0.7004, 0.8076, 0.1665],
        [0.9578, 0.0369, 0.6091]])
tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883]])
tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843]])


In [29]:
print(x[0]) 
print(x[:,0]) 
print(x[0,1]) 
print(x[0][1]) 

tensor([0.6994, 0.1726, 0.3281])
tensor([0.6994, 0.4561, 0.1526, 0.7004, 0.9578])
tensor(0.1726)
tensor(0.1726)


In [30]:
print(x) 
r = [1,2,3]  
print(x[r]) 
c = [0,1,2] 
y = x[r,c] 
print(y)  
#r是行索引，c是列索引 
#取出(1,0),(2,1),(3,2)三个位置的值 

tensor([[0.6994, 0.1726, 0.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665],
        [0.9578, 0.0369, 0.6091]])
tensor([[0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665]])
tensor([0.4561, 0.5134, 0.1665])


In [31]:
y = x[0,:] 
print(y) 
y += 1 
print(y) 
print(x) 

tensor([0.6994, 0.1726, 0.3281])
tensor([1.6994, 1.1726, 1.3281])
tensor([[1.6994, 1.1726, 1.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [0.7004, 0.8076, 0.1665],
        [0.9578, 0.0369, 0.6091]])


In [32]:
y = x[-2:] 
y += 1 
print(x) 
print(y) 

tensor([[1.6994, 1.1726, 1.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [1.7004, 1.8076, 1.1665],
        [1.9578, 1.0369, 1.6091]])
tensor([[1.7004, 1.8076, 1.1665],
        [1.9578, 1.0369, 1.6091]])


In [33]:
indices = torch.LongTensor([0,2]) # Long
print(indices) 
print(indices.dtype) 
z = torch.index_select(x,0,indices) 
print(z) 
z = torch.index_select(x,1,indices) 
print(z) 
z += 1 
print(x) 
print(z) 
#0指行，1指列 

tensor([0, 2])
torch.int64
tensor([[1.6994, 1.1726, 1.3281],
        [0.1526, 0.5134, 0.4883]])
tensor([[1.6994, 1.3281],
        [0.4561, 0.0843],
        [0.1526, 0.4883],
        [1.7004, 1.1665],
        [1.9578, 1.6091]])
tensor([[1.6994, 1.1726, 1.3281],
        [0.4561, 0.4384, 0.0843],
        [0.1526, 0.5134, 0.4883],
        [1.7004, 1.8076, 1.1665],
        [1.9578, 1.0369, 1.6091]])
tensor([[2.6994, 2.3281],
        [1.4561, 1.0843],
        [1.1526, 1.4883],
        [2.7004, 2.1665],
        [2.9578, 2.6091]])


In [34]:
x = torch.randn(5,3,dtype=torch.float)
print(x) 
mask = x.ge(0.5) 
print(mask) 
print(torch.masked_select(x,mask)) 
y = x[x>0.5] 
print(y) 
y += 1 
print(y) 
print(x) 
#张量 mask须跟input张量有相同数量的元素数目，但形状或维度不需要相同。 
#注意： 返回的张量不与原始张量共享内存空间。

tensor([[-0.0495, -0.3364, -0.2289],
        [ 1.0327,  0.9913,  0.2418],
        [-0.8537, -1.5645,  1.7854],
        [ 0.9044, -1.0463,  0.3041],
        [ 1.0053,  0.4246, -0.1090]])
tensor([[False, False, False],
        [ True,  True, False],
        [False, False,  True],
        [ True, False, False],
        [ True, False, False]])
tensor([1.0327, 0.9913, 1.7854, 0.9044, 1.0053])
tensor([1.0327, 0.9913, 1.7854, 0.9044, 1.0053])
tensor([2.0327, 1.9913, 2.7854, 1.9044, 2.0053])
tensor([[-0.0495, -0.3364, -0.2289],
        [ 1.0327,  0.9913,  0.2418],
        [-0.8537, -1.5645,  1.7854],
        [ 0.9044, -1.0463,  0.3041],
        [ 1.0053,  0.4246, -0.1090]])


In [35]:
print(x) 
y = x.view(15) 
z = x.view(-1,5) 
print(y) 
print(z) 
print(y.shape,z.shape) 
print(x) 
x += 1 
print(x) 
print(y) 
y += 1 
print(x) 
print(y) 
#view()返回的新tensor和源tensor共享内存 
#列顺序

tensor([[-0.0495, -0.3364, -0.2289],
        [ 1.0327,  0.9913,  0.2418],
        [-0.8537, -1.5645,  1.7854],
        [ 0.9044, -1.0463,  0.3041],
        [ 1.0053,  0.4246, -0.1090]])
tensor([-0.0495, -0.3364, -0.2289,  1.0327,  0.9913,  0.2418, -0.8537, -1.5645,
         1.7854,  0.9044, -1.0463,  0.3041,  1.0053,  0.4246, -0.1090])
tensor([[-0.0495, -0.3364, -0.2289,  1.0327,  0.9913],
        [ 0.2418, -0.8537, -1.5645,  1.7854,  0.9044],
        [-1.0463,  0.3041,  1.0053,  0.4246, -0.1090]])
torch.Size([15]) torch.Size([3, 5])
tensor([[-0.0495, -0.3364, -0.2289],
        [ 1.0327,  0.9913,  0.2418],
        [-0.8537, -1.5645,  1.7854],
        [ 0.9044, -1.0463,  0.3041],
        [ 1.0053,  0.4246, -0.1090]])
tensor([[ 0.9505,  0.6636,  0.7711],
        [ 2.0327,  1.9913,  1.2418],
        [ 0.1463, -0.5645,  2.7854],
        [ 1.9044, -0.0463,  1.3041],
        [ 2.0053,  1.4246,  0.8910]])
tensor([ 0.9505,  0.6636,  0.7711,  2.0327,  1.9913,  1.2418,  0.1463, -0.5645,
        

In [36]:
x = torch.randn(4,6) 
print(x) 
y = x.view(-1,2) 
print(y) 
y = x.view(4,-1) 
print(y) 
y = x.view(3,8) 
print(y) 
# -1表示对该维的数目不做限制

tensor([[ 1.8350,  1.9157, -1.1458,  0.7938, -0.6232, -0.0285],
        [-1.1522, -0.0496,  0.9861,  0.8777, -0.0873, -0.3290],
        [-1.3862,  1.3785,  1.3079,  0.5811,  0.1424, -0.1212],
        [-2.5044,  0.6684, -0.7104, -0.8293, -0.6834,  0.1488]])
tensor([[ 1.8350,  1.9157],
        [-1.1458,  0.7938],
        [-0.6232, -0.0285],
        [-1.1522, -0.0496],
        [ 0.9861,  0.8777],
        [-0.0873, -0.3290],
        [-1.3862,  1.3785],
        [ 1.3079,  0.5811],
        [ 0.1424, -0.1212],
        [-2.5044,  0.6684],
        [-0.7104, -0.8293],
        [-0.6834,  0.1488]])
tensor([[ 1.8350,  1.9157, -1.1458,  0.7938, -0.6232, -0.0285],
        [-1.1522, -0.0496,  0.9861,  0.8777, -0.0873, -0.3290],
        [-1.3862,  1.3785,  1.3079,  0.5811,  0.1424, -0.1212],
        [-2.5044,  0.6684, -0.7104, -0.8293, -0.6834,  0.1488]])
tensor([[ 1.8350,  1.9157, -1.1458,  0.7938, -0.6232, -0.0285, -1.1522, -0.0496],
        [ 0.9861,  0.8777, -0.0873, -0.3290, -1.3862,  1.3785,  1.3

In [1]:
print(x) 
print(x_cp) 
x_cp = x.clone().viw(15) 
x += 1 
print(x) 
print(x_cp) 
x_cp += 3 
print(x) 
print(x_cp) 
#克隆后的不共享内存 

NameError: name 'x' is not defined

In [38]:
x = torch.arange(1,3) 
print(x) 
print(x.size()) 
x = torch.arange(1,3).view(1,2) 
print(x) 
print(x.size()) 
# unsqueeze 拓展维数

tensor([1, 2])
torch.Size([2])
tensor([[1, 2]])
torch.Size([1, 2])


In [39]:
x = torch.arange(1,3).view(1,2) 
y = torch.arange(1,4).view(3,1) 
print(y) 
print(x + y) 
# 广播机制的语法规则，两个多维 

tensor([[1],
        [2],
        [3]])
tensor([[2, 3],
        [3, 4],
        [4, 5]])


In [40]:
x = torch.tensor([1,2]) 
y = torch.tensor([3,4]) 
id_before = id(y) 
y = y + x 
print(id(y) == id_before) 
print(id(y)) 
print(id_before) 

False
1479138705136
1479138836704


In [41]:
x = torch.tensor([1,2]) 
y = torch.tensor([3,4]) 
id_before = id(y) 
y[:] = y + x 
print(id(y) == id_before) 
print(id(y)) 
print(id_before)

True
1479138837984
1479138837984


In [42]:
x = torch.tensor([1,2])
y = torch.tensor([3,4]) 
id_before = id(y) 
torch.add(x,y,out=y) #或y += x和y.add_(x) 
print(id(y) == id_before) 

True


In [43]:
#Tensor转Numpy，共享内存 
a = torch.ones(5) 
print(a) 
b = a.numpy() 
print(a,b) 
a += 1 
print(a,b) 
b += 1 
print(a,b) 

tensor([1., 1., 1., 1., 1.])
tensor([1., 1., 1., 1., 1.]) [1. 1. 1. 1. 1.]
tensor([2., 2., 2., 2., 2.]) [2. 2. 2. 2. 2.]
tensor([3., 3., 3., 3., 3.]) [3. 3. 3. 3. 3.]


In [44]:
#Numpy转Tensor，共享内存 
a = numpy.ones(5) 
b = torch.from_numpy(a) 
print(a,b) 
a += 1 
print(a,b) 
b += 1 
print(a,b) 

[1. 1. 1. 1. 1.] tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
[2. 2. 2. 2. 2.] tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
[3. 3. 3. 3. 3.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [45]:
c = torch.tensor(a) 
a += 1 
print(a,c) 
#这种办法不共享内存 

[4. 4. 4. 4. 4.] tensor([3., 3., 3., 3., 3.], dtype=torch.float64)


In [3]:
from time import time 
a = torch.ones(1000) 
b = torch.ones(1000) 
start = time() 
c = torch.zeros(1000) 
for i in range(1000): 
c[i] = a[i] + b[i] 
print(time() - start) 
# 解释性语言和编译性语言 
# python的加速 

IndentationError: expected an indented block (4210203105.py, line 7)

In [47]:
start = time() 
d = a + b 
print(time() - start)

NameError: name 'time' is not defined