In [1]:
import torch
import numpy as np

In [8]:
tensor = torch.rand(5, 8)
print(tensor)
# 索引第2至3行
rows = tensor[1:3, :] #Python的索引从0开始，所以第2至3行是索引1:3
print(rows)
# 索引奇数列
odd = tensor[:, 1::2]
print(odd)
# 索引所有>0.6的元素
elements = tensor[tensor > 0.6]
print(elements)

tensor([[0.3845, 0.8023, 0.3900, 0.7975, 0.4371, 0.7600, 0.0333, 0.5866],
        [0.3393, 0.4383, 0.8336, 0.6824, 0.0569, 0.6019, 0.4775, 0.3479],
        [0.0238, 0.8568, 0.9756, 0.9004, 0.4056, 0.0124, 0.3466, 0.9202],
        [0.1907, 0.8274, 0.4341, 0.6555, 0.1323, 0.6711, 0.4876, 0.3412],
        [0.2890, 0.7610, 0.4078, 0.1721, 0.2079, 0.8695, 0.9070, 0.6485]])
tensor([[0.3393, 0.4383, 0.8336, 0.6824, 0.0569, 0.6019, 0.4775, 0.3479],
        [0.0238, 0.8568, 0.9756, 0.9004, 0.4056, 0.0124, 0.3466, 0.9202]])
tensor([[0.8023, 0.7975, 0.7600, 0.5866],
        [0.4383, 0.6824, 0.6019, 0.3479],
        [0.8568, 0.9004, 0.0124, 0.9202],
        [0.8274, 0.6555, 0.6711, 0.3412],
        [0.7610, 0.1721, 0.8695, 0.6485]])
tensor([0.8023, 0.7975, 0.7600, 0.8336, 0.6824, 0.6019, 0.8568, 0.9756, 0.9004,
        0.9202, 0.8274, 0.6555, 0.6711, 0.7610, 0.8695, 0.9070, 0.6485])


In [7]:
x = torch.rand(1, 5)
print(x)
y = torch.rand(6, 1)
print(y)
# 按照广播机制相加
s = x + y
print(s)
t = x.expand(6, 5) + y.expand(6, 5) #需要x和y的形状相同，因此需要扩展为6*5
print(t)
# 将广播相加的结果赋值给x
x = t
print(x)

tensor([[0.6521, 0.7378, 0.8099, 0.1083, 0.5924]])
tensor([[0.2738],
        [0.7196],
        [0.2537],
        [0.0193],
        [0.8479],
        [0.7961]])
tensor([[0.9258, 1.0115, 1.0836, 0.3821, 0.8661],
        [1.3716, 1.4573, 1.5294, 0.8279, 1.3119],
        [0.9057, 0.9915, 1.0636, 0.3620, 0.8461],
        [0.6714, 0.7571, 0.8292, 0.1276, 0.6117],
        [1.4999, 1.5856, 1.6577, 0.9562, 1.4402],
        [1.4481, 1.5338, 1.6059, 0.9044, 1.3884]])
tensor([[0.9258, 1.0115, 1.0836, 0.3821, 0.8661],
        [1.3716, 1.4573, 1.5294, 0.8279, 1.3119],
        [0.9057, 0.9915, 1.0636, 0.3620, 0.8461],
        [0.6714, 0.7571, 0.8292, 0.1276, 0.6117],
        [1.4999, 1.5856, 1.6577, 0.9562, 1.4402],
        [1.4481, 1.5338, 1.6059, 0.9044, 1.3884]])
tensor([[0.9258, 1.0115, 1.0836, 0.3821, 0.8661],
        [1.3716, 1.4573, 1.5294, 0.8279, 1.3119],
        [0.9057, 0.9915, 1.0636, 0.3620, 0.8461],
        [0.6714, 0.7571, 0.8292, 0.1276, 0.6117],
        [1.4999, 1.5856, 1.6577, 0.956

In [10]:
a1 = torch.rand(8, 8)
b1 = torch.rand(8, 8)
print(a1)
print(b1)
# 将张量转化为numpy的array
a2 = a1.numpy()
b2 = b1.numpy()
print(a2)
print(b2)
# 做矩阵相乘
result1 = np.dot(a2, b2)
print(result1)
# 将结果转化为pytorch下的张量类型
result2 = torch.from_numpy(result1)
print(result2)

tensor([[0.6312, 0.0346, 0.4947, 0.1180, 0.8333, 0.7621, 0.1692, 0.2308],
        [0.8700, 0.1468, 0.9688, 0.6872, 0.8230, 0.4949, 0.2792, 0.6055],
        [0.4546, 0.5857, 0.5158, 0.9610, 0.6467, 0.4186, 0.2254, 0.6105],
        [0.2496, 0.0696, 0.4281, 0.9999, 0.9800, 0.4074, 0.7311, 0.7775],
        [0.2710, 0.7932, 0.9639, 0.6213, 0.2539, 0.0895, 0.9540, 0.9816],
        [0.6754, 0.9037, 0.8634, 0.5478, 0.0716, 0.1277, 0.5999, 0.9579],
        [0.1519, 0.8082, 0.6753, 0.2387, 0.7902, 0.9197, 0.6253, 0.8944],
        [0.6988, 0.0380, 0.4196, 0.9634, 0.0460, 0.3709, 0.9244, 0.8662]])
tensor([[0.3702, 0.6168, 0.9743, 0.5974, 0.2216, 0.1444, 0.6773, 0.2635],
        [0.1867, 0.7175, 0.7584, 0.0278, 0.8096, 0.9945, 0.4364, 0.4692],
        [0.7686, 0.3552, 0.0374, 0.3287, 0.2410, 0.1356, 0.7760, 0.6293],
        [0.8864, 0.5255, 0.5970, 0.0018, 0.7080, 0.0342, 0.9010, 0.4744],
        [0.0436, 0.9812, 0.2990, 0.1972, 0.3056, 0.4883, 0.5103, 0.7287],
        [0.0266, 0.3527, 0.9052, 0.86