In [7]:
import numpy as np

多维性

In [8]:
arr = np.array(5) #创建0维ndarray
print(arr)
print('arr的维度:' ,arr.ndim)

5
arr的维度: 0


In [9]:
arr = np.array([1, 2, 3])  
print(arr)
print('arr的维度:', arr.ndim)

[1 2 3]
arr的维度: 1


In [10]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) 
print(arr)
print('arr的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]]
arr的维度: 2


同质性

In [11]:
arr = np.array([1, 'hello']) #不同数据类型会被强制转换成相同类型
print(arr)

['1' 'hello']


In [12]:
arr = np.array([1, 2.5]) #1变成了浮点数
print(arr)

[1.  2.5]
