In [1]:
import numpy as np

In [2]:
arr = np.array([[1, 2, 3], [4, 5, 6]]) #两行三列
arr0 = np.array(5)
print(arr)
print('数组的形状:', arr.shape)
print(arr0)
print('数组0的形状:', arr0.shape)

[[1 2 3]
 [4 5 6]]
数组的形状: (2, 3)
5
数组0的形状: ()


In [3]:
print(arr)
print('数组的维度:', arr.ndim)

[[1 2 3]
 [4 5 6]]
数组的维度: 2


In [4]:
print(arr)
print('元素的个数:', arr.size)
print(arr0)
print('元素的个数:', arr0.size)

[[1 2 3]
 [4 5 6]]
元素的个数: 6
5
元素的个数: 1


In [5]:
print('数据类型:', arr.dtype)

arr = np.array([[1, 2.5, 3], [4, 5, 6]])
print(arr)
print('数据类型:', arr.dtype)

数据类型: int64
[[1.  2.5 3. ]
 [4.  5.  6. ]]
数据类型: float64


In [6]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
print('arr的转置;', arr.T)

arr的转置; [[1 4]
 [2 5]
 [3 6]]


itemsize: 单个元素占用的字节内存数
nbytes: 数组总站用内存，size * itemsize
flags: 内存存储方式