In [21]:
import numpy as np

基础创建

In [22]:
data = [4, 5, 6]
arr1 = np.array(data)
print(arr1)
arr2 = np.array(data, dtype=np.float64) #dtype强制转换类型
print(arr2)

#copy
arr = np.copy(arr1) #arr的元素和参数里的数组相同，但不是一个数组
print(arr)
arr1 = [4, 5, 8]
print(arr)

[4 5 6]
[4. 5. 6.]
[4 5 6]
[4 5 6]


预定义形状的创建

In [23]:
#全0
arr = np.zeros((2,3)) #定义两行三列的全零
print(arr)
print(arr.dtype)
arr = np.zeros((2,3), dtype=int) 
print(arr)
print(arr.dtype)

[[0. 0. 0.]
 [0. 0. 0.]]
float64
[[0 0 0]
 [0 0 0]]
int32


In [24]:
arr = np.zeros((3,)) #少维度就不写
print(arr)

[0. 0. 0.]


In [25]:
#全1
arr = np.ones((2,3), dtype=int)
print(arr)

[[1 1 1]
 [1 1 1]]


In [26]:
#未初始化
arr = np.empty((4,5)) #随即填充
print(arr)
arr = np.empty((4,5), dtype=int)
print(arr)

[[1.89146896e-307 1.37961302e-306 6.23053614e-307 6.23053954e-307
  9.34609790e-307]
 [8.45593934e-307 9.34600963e-307 1.86921143e-306 6.23061763e-307
  8.90104239e-307]
 [6.89804132e-307 1.33512376e-306 6.89806849e-307 9.34609790e-307
  1.69121096e-306]
 [1.05700515e-307 2.04712906e-306 7.56589622e-307 1.11258277e-307
  8.90111708e-307]]
[[ 1467367570  1075945796  1086075473  1076198007  -772112564]
 [ 1076012258 -1485474779  1075594356  1324566179  1075942991]
 [ 1263501985  1076156443  1189017192  1076270790  -763810881]
 [ 1076283493 -1424568406  1076206955 -1215729782  1076102499]]


In [27]:
#指定其他数值
arr = np.full((2,3), 1234)
print(arr)

[[1234 1234 1234]
 [1234 1234 1234]]


In [28]:
#like
print(arr)
arr1 = np.zeros_like(arr) #构建形状相同的,可用dtype转换类型,否则照搬原本类型
print(arr1)
arr2 = np.ones_like(arr)
print(arr2)
arr3 = np.full_like(arr, 12)
print(arr3)
arr4 = np.empty_like(arr, dtype=float)
print(arr4)

[[1234 1234 1234]
 [1234 1234 1234]]
[[0 0 0]
 [0 0 0]]
[[1 1 1]
 [1 1 1]]
[[12 12 12]
 [12 12 12]]
[[0. 0. 0.]
 [0. 0. 0.]]


基于数值范围

In [29]:
#等差数列
arr= np.arange(1,10,3) #start,end,step 包含start 不包含end
print(arr)

[1 4 7]


In [30]:
#等间隔数列
arr = np.linspace(1,10,5) #start,end,num 包含end
print(arr)
arr = np.linspace(1,10,5, dtype=int) 
print(arr)

[ 1.    3.25  5.5   7.75 10.  ]
[ 1  3  5  7 10]


In [31]:
#对数间隔数列
arr = np.logspace(0,4,3,base=2) #start,end,num 包含end 可用dtype,默认为浮点数,以10为底
#0到4分成三分,得0,2,4 取2为底的指数,得1,4,16
print(arr)

[ 1.  4. 16.]


特殊矩阵生成

In [32]:
#单位矩阵
arr = np.eye(4)
print(arr)
arr1 = np.eye(3,4,dtype=int)
print(arr1)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]]


In [33]:
#对角矩阵
arr = np.diag([1,2,3,5])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 5]]


随机数组的生成

In [34]:
#0-1间均匀分布随机浮点数
arr = np.random.rand(2,3)
print(arr)

[[0.2723164  0.71860593 0.78300361]
 [0.85032764 0.77524489 0.03666431]]


In [35]:
#生成指定范围区间均匀分布随机浮点数
arr = np.random.uniform(3,6,(2,3)) #start,end,shape 包含start 不包含end
print(arr)

[[3.35008121 5.2538421  3.71765465]
 [3.76441804 5.57287659 5.84933708]]


In [36]:
#生成指定范围区间均匀分布随机整数
arr = np.random.randint(3,30,(2,3)) #start,end,shape 包含start 不包含end 一维数组则shape直接输入一个int即可
print(arr)

[[28 17  3]
 [13 14  9]]


In [37]:
#标准正太分布随机数组
arr = np.random.randn(2,3)
print(arr)

[[-1.6164342  -0.34456648 -0.38270796]
 [ 0.67826665  0.75069092 -1.78473676]]


In [38]:
#任意正态分布随机数组
arr = np.random.normal(10,1,10) #mean std size size也可以是元组 创建一个矩阵或高阶张量
print(arr)

[ 9.39996651 10.71497611 10.50853898 10.68916887  9.1460065   9.87803581
  8.71214521  8.16672642  9.29434645 10.62176588]


设置随机种子

In [39]:
np.random.seed(20) #设置种子后随机数组生成就一致了
arr = np.random.randint(1,10,(2,5))
print(arr)

[[4 5 7 8 3]
 [1 7 9 6 4]]
