索引从0开始

In [3]:
import numpy as np

一维数组

In [5]:
arr = np.random.randint(1,100,30)
print(arr)

[30 98 92 42 54 48 59 88 77 80 68 24 44 45 52 57 84 73 90 12 88 88 14 47
 32 27 59 32 52 16]


In [13]:
print(arr[3])
print(arr[:])
print(arr[2:6]) #start:end 含start 不含end
print(arr[(arr>10)&(arr<70)]) #布尔索引 支持& |
print(arr[slice(2,6)]) #slice中可写 start end step 不写step等价于2:6

42
[30 98 92 42 54 48 59 88 77 80 68 24 44 45 52 57 84 73 90 12 88 88 14 47
 32 27 59 32 52 16]
[92 42 54 48]
[30 42 54 48 59 68 24 44 45 52 57 12 14 47 32 27 59 32 52 16]
[92 42 54 48]


二维数组

In [15]:
arr = np.random.randint(1,100,(4,6))
print(arr)

[[46 88 74 89 19 32]
 [41 32  1 30 21 68]
 [15 57 23 28 90 52]
 [73 75  9  7 46 90]]


In [24]:
print(arr[0,3])
print(arr[:,3])
print(arr[1:3,3])
print(arr[arr>50]) #对二维数组用布尔索引返回一维数组

print(arr[2][arr[2]>50]) #第二行所有大于50的树
print(arr[:,3][arr[:,3]>50]) #第三列所有大于50的数

89
[89 30 28  7]
[30 28]
[88 74 89 68 57 90 52 73 75 90]
[57 90 52]
[89]
