In [34]:
import numpy as np

算术运算

In [35]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a+b)
print(a-b)
print(a*b)
print(a/b) #乘除法是对应位置运算 而非矩阵运算
print(a**2)
print(a**b)

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[1 4 9]
[  1  32 729]


In [36]:
a = [1,2,3]
b = [4,5,6]
print(a+b) #list array运算规则不同

[1, 2, 3, 4, 5, 6]


In [37]:
t = np.array([[1,2,3],[4,5,6]])
d = np.array([[7,8,9],[10,11,12]])
print(t+d)
print(t-d)
print(t*d)
print(t/d)
print(t**2)

[[ 8 10 12]
 [14 16 18]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 7 16 27]
 [40 55 72]]
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]
[[ 1  4  9]
 [16 25 36]]


In [38]:
print(t+3) #每个元素都和标量运算

[[4 5 6]
 [7 8 9]]


广播机制规则 


1：屁股对齐（右对齐）

如果两个数组的维度数量不一样，先把它们的最右边（尾部）对齐。

比如：一个形状是 (4, 3)，另一个是 (3,)。就把它们右边的 3 对齐。


规则 2：缺啥补啥（往左边补 1）

对齐后，如果哪个数组的维度比较少（比较短），就在它的最左边补上数字 1，直到两个数组的维度长度一样为止。

比如：(3,) 比 (4, 3) 短，就在左边补个 1，变成 (1, 3)。


规则 3：检查能不能拉伸（兼容原则）

现在两个数组一样长了，我们从左到右逐个对比每一位的数字。只要满足下面任意一种情况，就是兼容的（可以广播）：

相等：两个数字一样（比如都是 3）。

其中一个是 1：只要有一个是 1，它就可以被无限拉伸去迁就另一个数字。

如果既不相等，也没有一个是 1（比如一个是 4，一个是 5），那就直接报错，没法算了！

In [39]:
a = np.array([1,2,3])
b = np.array([[4],[5],[6]])
print(a+b)
print(a-b)

[[5 6 7]
 [6 7 8]
 [7 8 9]]
[[-3 -2 -1]
 [-4 -3 -2]
 [-5 -4 -3]]


矩阵运算

In [40]:
t = np.array([[1,2,3],[4,5,6]])
d = np.array([[7,8],[9,10],[11,12]])
print(t@d) #优先级与乘除法一致

[[ 58  64]
 [139 154]]


In [41]:
a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
c = np.array([[4],[5],[6]])
print(b@a) #a:3*1
print(a@c) #a:1*3
#NumPy不区分行列向量，会根据运算自动变换为行或列向量

[14 32]
[32]
