In [2]:
import numpy as np

基本数学函数

In [3]:
#计算平方根
print(np.sqrt(9))
print(np.sqrt([1,4,9]))
arr = np.array([1,4,9])
print(np.sqrt(arr))

3.0
[1. 2. 3.]
[1. 2. 3.]


In [4]:
#计算指数 e^x
print(np.exp(2))
print(np.exp([1,4,9]))
print(np.exp(arr))

7.38905609893065
[2.71828183e+00 5.45981500e+01 8.10308393e+03]
[2.71828183e+00 5.45981500e+01 8.10308393e+03]


In [5]:
#计算自然对数 lnx
print(np.log(2.71))

0.9969486348916096


In [6]:
#计算三角函数
print(np.sin(np.pi/2))
print(np.cos(np.pi))
print(np.tan(np.pi/2))

1.0
-1.0
1.633123935319537e+16


In [7]:
#计算绝对值
arr = np.array([1,-1,2,-2])
print(np.abs(arr))

[1 1 2 2]


In [8]:
#计算a^b
print(np.power(arr,3))

[ 1 -1  8 -8]


In [9]:
#四舍五入
print(np.round(3.4))
print(np.round(4.5))
print(np.round(4.51)) #五舍 大于五入

3.0
4.0
5.0


In [10]:
#向上/下取整
arr = np.array([1.4,2.5,3.6])
print(np.ceil(arr))
print(np.floor(arr))

[2. 3. 4.]
[1. 2. 3.]


In [11]:
#检测缺失值NaN
np.isnan([1,2,np.nan,3])

array([False, False,  True, False])

统计函数

In [12]:
arr = np.random.randint(1,20,8)
print(arr)

[ 4 19  8  7  7  5 17  5]


In [13]:
#求和函数
print(np.sum(arr))

72


In [14]:
#平均值函数
print(np.mean(arr))

9.0


In [15]:
#中位数函数
print(np.median(arr))

7.0


In [16]:
#标准差/方差函数
print(np.var(arr)) #方差
print(np.std(arr)) #标准差

28.75
5.361902647381804


In [17]:
#最值函数
print(np.max(arr))
print(np.min(arr))

19
4


In [18]:
#分位数函数
print(arr)
print(np.percentile(arr,20)) #0.2*(8-1)=1.4, 13+(14-13)*0.4=13.4
print(np.percentile(arr,0))

[ 4 19  8  7  7  5 17  5]
5.0
4.0


In [19]:
#累计和/积函数
print(arr)
print(np.cumsum(arr))
print(np.cumprod(arr))

[ 4 19  8  7  7  5 17  5]
[ 4 23 31 38 45 50 67 72]
[       4       76      608     4256    29792   148960  2532320 12661600]


比较函数

In [20]:
#大于/小于/等于 可引入广播机制
print(np.greater([3,4,5,6,7],5))
print(np.greater([3,4,5],[4,4,4]))
print(np.greater_equal([3,4,5],[4,4,4]))

print(np.less([3,4,5,6,7],5))
print(np.less([3,4,5],[4,4,4]))

print(np.equal([3,4,5,6,7],5))

[False False False  True  True]
[False False  True]
[False  True  True]
[ True  True False False False]
[ True False False]
[False False  True False False]


In [21]:
#与 或 非
print(np.logical_and([1,1],[1,0])) #全为非零(包括NaN)是true 必须两个输入并且满足广播机制
print(np.logical_and([[1,1],[1,0]],[0,1]))

print(np.logical_or([1,1],[1,0])) #有非零就为true
print(np.logical_not([-1,0,1,2])) #仅有0是true

[ True False]
[[False  True]
 [False False]]
[ True  True]
[False  True False False]


In [22]:
#检查元素
print(np.any([[0,0,0,0],[0,1,0,1]], axis=0)) #是否至少有一个为true
#=0：沿着 行 的方向挤压/跨越。通俗地说，就是对每一列（竖着）进行操作。
#axis=1：沿着 列 的方向挤压/跨越。通俗地说，就是对每一行（横着）进行操作
#对于对每个元素都要有输出结果的函数 不支持axis
print(np.all([0,1,1,1])) #是否全体元素都为true

[False  True False  True]
False


In [25]:
#自定义条件
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.where(arr>3, arr, 0)) #条件 符合条件输出 不符合条件输出

score = np.random.normal(70,20,30)
print(score)
print(np.where(score>=60, np.where(score>=80, np.where(score>=90, '优秀', '良好'), '及格'), '不及格'),)

#select
conditions = [
    score>=90,
    (score>=80) & (score<90),
    (score>=60) & (score<80), #()不能省略 &|优先级高于不等号
    score<60
]
choices = [
    '优秀','良好','及格','不及格'
]
print(np.select(conditions, choices, default='未知'))

[[ 0  0  0  4  5]
 [ 6  7  8  9 10]]
[ 51.96237031  85.59754611  50.32689969  73.84877667  74.67560714
  23.52998122  75.04381857  57.20268642  33.65736268  20.97660513
  67.00390959  31.26239193  33.75313832 118.60381756  72.17153402
  68.42131506  35.25742434  59.94520483  75.33258019  83.38871419
  82.02685282  85.9170863   72.86029848  32.8799668   84.01733658
  79.89131186  97.31607057  28.81404505  68.52998514  60.69599226]
['不及格' '良好' '不及格' '及格' '及格' '不及格' '及格' '不及格' '不及格' '不及格' '及格' '不及格' '不及格'
 '优秀' '及格' '及格' '不及格' '不及格' '及格' '良好' '良好' '良好' '及格' '不及格' '良好' '及格' '优秀'
 '不及格' '及格' '及格']
['不及格' '良好' '不及格' '及格' '及格' '不及格' '及格' '不及格' '不及格' '不及格' '及格' '不及格' '不及格'
 '优秀' '及格' '及格' '不及格' '不及格' '及格' '良好' '良好' '良好' '及格' '不及格' '良好' '及格' '优秀'
 '不及格' '及格' '及格']


排序函数

In [28]:
arr = np.random.randint(1,101,10)

In [38]:
print(arr)
arr.sort() #改变数组本身
print(arr)

arr = np.random.randint(1,101,10)
print(arr)
print(np.sort(arr))
print(arr)

print(np.argsort(arr)) #排序后元素在原本数组中的索引

print(np.unique(arr)) #去重排序

[ 50  89  52  49  12  23  18 100  26  69]
[ 12  18  23  26  49  50  52  69  89 100]
[ 6  8 81 51 87  8 24 18 98 28]
[ 6  8  8 18 24 28 51 81 87 98]
[ 6  8 81 51 87  8 24 18 98 28]
[0 1 5 7 6 9 3 2 4 8]
[ 6  8 18 24 28 51 81 87 98]


In [36]:
scores = np.array([[85, 60],
                   [70, 95],
                   [90, 50]])
print(np.sort(scores)) #默认axis=1 每行排序
print(np.sort(scores, axis=0))

[[60 85]
 [70 95]
 [50 90]]
[[70 50]
 [85 60]
 [90 95]]


In [42]:
#数组拼接 严格相等不可广播
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate((arr1, arr2)))
#axis=0 按行拼接； axis=1 按列拼接  区分与聚合函数的区别
#一维向量不会自适应变成行向量或者列向量而是直接不可参与拼接 eg [1,2,3,4,5]参与拼接直接报错 只能是[[1,2,3,4,5]]/[[1],[2],[3],[4],[5]]

[1 2 3 4 5 6]


In [46]:
#数组分割
print(arr)
print(np.split(arr,2)) #不能等分直接报错
#axis=0按列切分

#axis=n实际规定的是按照第n维的索引变化进行操作！！！！！

print(np.split(arr,[2,4,6,8])) #按照索引切 索引位置元素放到后一个切片

[ 6  8 81 51 87  8 24 18 98 28]
[array([ 6,  8, 81, 51, 87]), array([ 8, 24, 18, 98, 28])]
[array([6, 8]), array([81, 51]), array([87,  8]), array([24, 18]), array([98, 28])]


In [48]:
#调整数组形状
print(arr)
print(np.reshape(arr,[5,2])) #必须可以等分 不然报错

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8]]) # 总共 8 个元素

# 我想把它变成 2 行，但不想算有几列 -> 直接写 -1
new_arr = arr.reshape(2, -1) 
print(new_arr.shape) # 输出: (2, 4)  <-- NumPy 自动算出了 8/2=4 列

# 我想把它强行拉成一维，不管原来多少行多少列 -> 直接写 -1
flat_arr = arr.reshape(-1)
print(flat_arr) # 输出: [1 2 3 4 5 6 7 8]

[ 6  8 81 51 87  8 24 18 98 28]
[[ 6  8]
 [81 51]
 [87  8]
 [24 18]
 [98 28]]
(2, 4)
[1 2 3 4 5 6 7 8]
