In [2]:
import numpy as np

数组的变形

In [3]:
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# --- 测试 flatten (副本) ---
flat_arr = arr.flatten()
print(flat_arr)
flat_arr[0] = 999  # 修改展平后的数组
print(flat_arr)
print("修改 flatten 后，原数组 arr：\n", arr)  # 原数组纹丝不动

# --- 测试 ravel (视图) ---
ravel_arr = arr.ravel()
ravel_arr[0] = 888  # 修改展平后的数组
print("修改 ravel 后，原数组 arr：\n", arr)    # 原数组的第一个元素也被改了！

#reshape,flatten,ravel 不能接收axis

[1 2 3 4 5 6]
[999   2   3   4   5   6]
修改 flatten 后，原数组 arr：
 [[1 2 3]
 [4 5 6]]
修改 ravel 后，原数组 arr：
 [[888   2   3]
 [  4   5   6]]


In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("原始数组形状:", arr.shape)
print(arr, "\n")

# --- 1. order='C' (默认，按行优先 / C语言风格) ---
# 逻辑：先横着把第一行读完，再读第二行
flat_c = arr.flatten(order='C')
print("order='C' (按行):", flat_c)  
# 输出: [1 2 3 4 5 6]

# --- 2. order='F' (按列优先 / Fortran风格) ---
# 逻辑：先竖着把第一列读完，再读第二列...
flat_f = arr.flatten(order='F')
print("order='F' (按列):", flat_f)  
# 输出: [1 4 2 5 3 6]

# --- 3. order='A' (看原数组的内存布局决定) ---
# 逻辑：如果原数组在内存里是按列存的，就按F走；否则按C走。
# 因为我们是用 np.array 正常创建的，默认是C风格存储，所以结果通常和 'C' 一样。
flat_a = arr.flatten(order='A')
print("order='A' (自适应):", flat_a) 
# 输出: [1 2 3 4 5 6]

# --- 4. order='K' (完全按照元素在内存中实际出现的物理顺序) ---
# 逻辑：不管原本的轴是什么，只认内存里的真实排队顺序。
# 对于普通的连续数组，它看起来和 'C' 一模一样。
# （它的强大之处通常在处理过转置或切片后的复杂数组时才会显现）
flat_k = arr.flatten(order='K')
print("order='K' (内存物理顺序):", flat_k)
# 输出: [1 2 3 4 5 6]

原始数组形状: (2, 3)
[[1 2 3]
 [4 5 6]] 

order='C' (按行): [1 2 3 4 5 6]
order='F' (按列): [1 4 2 5 3 6]
order='A' (自适应): [1 2 3 4 5 6]
order='K' (内存物理顺序): [1 2 3 4 5 6]


随机打乱排序

In [5]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
print("洗牌前：", arr)

np.random.shuffle(arr)  # 直接在 arr 身上动手脚
print("洗牌后：", arr)  # arr 的顺序已经被彻底打乱了

#为原地操作(In-place) 会直接修改传入的原数组 没有返回值

洗牌前： [1 2 3 4 5 6 7 8]
洗牌后： [6 3 1 8 4 5 7 2]


In [6]:
#如果是多维数组 shuffle 永远只会打乱第 0 轴(也就是行的顺序) 每一行内部的元素顺序保持不变 不接收axis
arr = np.array([[ 1,  2,  3,  4],
                [ 5,  6,  7,  8],
                [ 9, 10, 11, 12]])

print("洗牌前：")
print(arr)

np.random.shuffle(arr)  # 只能在 axis=0 (行) 上动手脚

print("\n洗牌后（只有行的顺序变了，每行内部没变）：")
print(arr)

洗牌前：
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

洗牌后（只有行的顺序变了，每行内部没变）：
[[ 1  2  3  4]
 [ 9 10 11 12]
 [ 5  6  7  8]]


随机抽取样本

In [7]:
data = np.array(['苹果', '香蕉', '橘子', '葡萄', '西瓜'])

# 场景1：普通抽奖，随机抽 3 个水果（允许重复抽到同一个）
sample1 = np.random.choice(data, size=3, replace=True)
print("普通抽奖结果：", sample1)

# 场景2：不放回抽样，抽 3 个不同的水果（一旦抽中就不会再出现）
sample2 = np.random.choice(data, size=3, replace=False)
print("不放回抽奖结果：", sample2)

# 场景3：带权重的抽奖（比如想让“西瓜”有 80% 的概率被抽中）
# p 参数的长度必须和 data 一致，总和为 1
weights = [0.05, 0.05, 0.05, 0.05, 0.8] 
sample3 = np.random.choice(data, size=3, p=weights)
print("带权重的抽奖结果：", sample3)

#np.random.choice(a,size,replace,p)
#a：要从中抽样的数组或整数（如果是整数 n，则代表从 0 到 n-1 中抽取）。
#size：抽取的数量 数字或元组
#replace：是否放回（True 表示元素可以重复被抽到，False 表示抽走就不放回去了）。
#p：每个元素被抽到的概率权重（所有概率加起来必须等于 1）。

普通抽奖结果： ['橘子' '香蕉' '苹果']
不放回抽奖结果： ['香蕉' '橘子' '葡萄']
带权重的抽奖结果： ['西瓜' '西瓜' '西瓜']


文件的读写

In [9]:
import os

In [11]:
# 获取并打印当前的【绝对路径】（也就是你的“脚下”在哪里）
print("当前的工作目录是：", os.getcwd())

当前的工作目录是： D:\dsml\numpy学习


In [14]:
# --- 1. 准备工作：创建一个测试数组 ---
arr = np.array([[1, 2, 3], [4, 5, 6]])
print("原始数组形状：", arr.shape)

# --- 2. 确保文件夹存在 (防止报错) ---
# 如果当前目录下没有 'my_data_folder' 文件夹，就自动创建一个
if not os.path.exists(r'D:\dsml\my_data_folder'):
    os.makedirs(r'D:\dsml\my_data_folder')

# --- 3. 指定完整的路径和文件名进行保存 ---
# 这里的第一个参数直接写死了文件要存放的绝对/相对路径
np.save(r'D:\dsml\my_data_folder\my_custom_name.npy', arr) 
print("✅ 成功将数组保存到了 my_data_folder 文件夹下，命名为 my_custom_name.npy")

原始数组形状： (2, 3)
✅ 成功将数组保存到了 my_data_folder 文件夹下，命名为 my_custom_name.npy


In [17]:
# --- 1. 模拟一个稍大的二维数据矩阵 (5行5列) ---
big_data = np.arange(25).reshape(5, 5)
print("原始大数据：\n", big_data)

# --- 2. 使用切片提取你想要的特定区域 ---
# 规则：[起始行:结束行, 起始列:结束列] （注意：Python切片包含开头，不包含结尾）

# 场景A：提取左上角的 3行3列 (即第0-2行，第0-2列)
roi_area = big_data[0:3, 0:3] 

# 场景B：提取中间的两行，所有列 (即第1-2行，所有列用冒号 : 表示)
row_slice = big_data[1:3, :]

print("\n提取出的左上角区域：\n", roi_area)

# --- 3. 只把提取出来的区域单独保存 ---
np.save(r'D:\dsml\my_roi_region.npy', roi_area)
print("\n✅ 成功将裁剪后的区域单独保存为 my_roi_region.npy")

原始大数据：
 [[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

提取出的左上角区域：
 [[ 0  1  2]
 [ 5  6  7]
 [10 11 12]]

✅ 成功将裁剪后的区域单独保存为 my_roi_region.npy


In [19]:
# --- 1. 演示普通切片（视图 View）的风险 ---
# 普通切片只是给原数据开了个“窗口”，并没有真正复制数据
view_data = big_data[0:2, 0:2]  
view_data[0, 0] = 999  # 修改视图里的值

print("修改视图后，原始的 big_data 变成了：\n", big_data)
# ⚠️ 你会发现：原始数据也被连带修改了！这在处理重要数据时非常危险。

# --- 2. 演示如何生成完全独立的副本（Copy） ---
# 在切片后面加上 .copy()，就会开辟一块全新的内存来存数据
safe_copy = big_data[0:2, 0:2].copy() 
safe_copy[0, 0] = 888  # 修改副本里的值

print("\n修改副本后，原始的 big_data 依然是：\n", big_data)
# ✅ 此时原始数据纹丝不动，两者彻底脱钩！

修改视图后，原始的 big_data 变成了：
 [[999   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]

修改副本后，原始的 big_data 依然是：
 [[999   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 15  16  17  18  19]
 [ 20  21  22  23  24]]


In [22]:
# --- 1. 整体加载之前保存的文件 ---
loaded_arr = np.load(r'D:\dsml\my_data_folder\my_custom_name.npy')
print("从文件中加载回来的数组：\n", loaded_arr)

# --- 2. 对加载回来的数组再次进行切片提取 ---
# 比如我们只想读取这个文件里第一行的数据
first_row = loaded_arr[0, :] 
print("\n读取并提取出的第一行数据：", first_row)

从文件中加载回来的数组：
 [[1 2 3]
 [4 5 6]]

读取并提取出的第一行数据： [1 2 3]


In [23]:
# --- 1. 创建一个基于硬盘文件的“内存映射”数组 ---
# mode='r+' 表示可读可写；shape 必须和你当初保存的形状一致
# 它的原理是：不真正把数据读进内存，而是直接在硬盘上操作
mmap_arr = np.memmap(r'D:/dsml/my_roi_region.npy', dtype='int64', mode='r+', shape=(3, 3))

# --- 2. 直接读取硬盘上特定区域的值（完全不占内存！） ---
# 比如只读取这个巨型文件里的前两行、前两列
small_chunk = mmap_arr[0:2, 0:2]
print("从硬盘直接读取的小块数据：\n", small_chunk)

# --- 3. 甚至可以直接修改硬盘上的数据 ---
mmap_arr[0, 0] = 777 
mmap_arr.flush()  # 强制把修改写入硬盘
print("\n✅ 成功通过内存映射修改了硬盘上的文件数据！")

从硬盘直接读取的小块数据：
 [[    379676406402707 7166182912910098550]
 [8390891540278422567 7306090318169792882]]

✅ 成功通过内存映射修改了硬盘上的文件数据！
