In [2]:
import numpy as np

题目 1：温度数据分析

某城市一周的最高气温（℃）为 [28，30，29，31，32，30，29]。

计算平均气温、最高气温和最低气温。

找出气温超过 30℃ 的天数。

In [3]:
arr = np.array([28,30,29,31,32,30,29])
print('平均气温:%.3f'%np.average(arr))
print('最高气温:', np.max(arr))
print('最低气温:', np.min(arr))
print('气温超过30的天数:', np.sum(np.where(arr>30,1,0)))

平均气温:29.857
最高气温: 32
最低气温: 28
气温超过30的天数: 2


题目 2：学生成绩统计

某班级 5 名学生的数学成绩为 [85, 90, 78, 92, 88]。

计算成绩的平均分、中位数和标准差。

将成绩转换为百分制（假设满分为 10）。

In [4]:
score = np.array([85,90,78,92,88])
print(np.round(np.mean(score),2))
print(np.median(score))
print(np.round(np.std(score),3))
print(arr/100*10)

86.6
88.0
4.883
[2.8 3.  2.9 3.1 3.2 3.  2.9]


题目 3：矩阵运算

给定矩阵 A = [[1, 2], [3, 4]] 和 B = [[5, 6], [7, 8]]。

计算 A + B 和 A * B（逐元素乘法）。

计算 A 和 B 的矩阵乘法（点积）。

In [5]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])
print(a+b)
print(a*b)
print(a@b)

[[ 6  8]
 [10 12]]
[[ 5 12]
 [21 32]]
[[19 22]
 [43 50]]


题目 4：随机数据生成

生成一个 (3, 4) 的随机整数数组，范围 [0, 10)。

计算每列的最大值和每行的最小值。

将数组中的所有奇数替换为 -1。

In [6]:
arr = np.random.randint(0,10,(3,4))
print(arr)
print('每列最大值:', np.max(arr,axis=0))
print('每行最小值:', np.min(arr,axis=1))
conditions = [
    arr%2 == 1,
    arr%2 == 0
]
choices = [
    -1, arr
]
arr0 = np.select(conditions, choices) 
#arr0 = np.where(arr%2==1,-1,arr)
#arr[arr%2==-1] = -1
print(arr0)

[[9 1 9 2]
 [7 0 8 5]
 [8 8 2 1]]
每列最大值: [9 8 9 5]
每行最小值: [1 0 1]
[[-1 -1 -1  2]
 [-1  0  8 -1]
 [ 8  8  2 -1]]


题目 5：数组变形

创建一个 1 到 12 的一维数组，并转换为 (3, 4) 的二维数组。

计算每行的和与每列的平均值。

将数组展平为一维数组。

In [7]:
arr = np.arange(1,13)
arr = arr.reshape(3,4)
print(arr)
print('每行平均值:',np.mean(arr,axis=1))
print('每列平均值:',np.mean(arr,axis=0))
arr = arr.reshape(-1)
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
每行平均值: [ 2.5  6.5 10.5]
每列平均值: [5. 6. 7. 8.]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


题目6：布尔索引

生成一个 (5, 5) 的随机数组，范围 [0, 20)。

找出数组中大于 10 的元素。

将所有大于 10 的元素替换为 0。

In [8]:
arr = np.random.randint(0,20,(5,5))
print(arr)
arr[arr>10] = 0
print(arr)

[[ 1  7  4 18  7]
 [19 18 11  9  6]
 [11  5 18 16  1]
 [11  8  2  2  1]
 [18 13 12 11 17]]
[[1 7 4 0 7]
 [0 0 0 9 6]
 [0 5 0 0 1]
 [0 8 2 2 1]
 [0 0 0 0 0]]


题目 7：统计函数应用

某公司 6 个月的销售额（万元）为 [120, 135, 110, 125, 130, 140]。

计算销售额的总和、均值和方差。

找出销售额最高的月份和最低的月份。

In [9]:
sale = np.array([120,135,110,125,130,140])
print(np.sum(sale))
print(np.mean(sale))
print(np.var(sale))
print(np.argmax(sale)+1)
print(np.argmin(sale)+1)

760
126.66666666666667
97.22222222222223
6
3


题目 8：数组拼接

给定 A = [1, 2, 3] 和 B = [4, 5, 6]。

将 A 和 B 水平拼接为一个新数组。

将 A 和 B 垂直拼接为一个新数组。

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,6])
print(np.concatenate([[a],[b]],axis=1))
print(np.hstack((a,b)))
print(np.concatenate([[a],[b]],axis=0))
print(np.vstack((a,b)))

[[1 2 3 4 5 6]]
[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]
[[1 2 3]
 [4 5 6]]


题目 9：唯一值与排序

给定数组 [2, 1, 2, 3, 1, 4, 3]。

找出数组中的唯一值并排序。

计算每个唯一值出现的次数。

In [28]:
arr = np.array([2,1,2,3,1,4,3])
u_arr,count = np.unique(arr,return_counts=True)
print(u_arr)
print('元素出现次数:', count)

for i in u_arr:
    print('%d出现次数:'%i, np.sum(np.where(arr==i,1,0)))

[1 2 3 4]
元素出现次数: [2 2 2 1]
1出现次数: 2
2出现次数: 2
3出现次数: 2
4出现次数: 1


题目 20：综合应用

某商店 5 天的销售额（万元）和成本（万元）如下：

销售额：[20, 25, 22, 30, 28]

成本：[15, 18, 16, 22, 20]

计算每天的利润（销售额 - 成本）。

计算利润的平均值和标准差。

找出利润最高的天数。

In [34]:
sales = np.array([20,25,22,30,28])
cost = np.array([15,18,16,22,20])
print(sales-cost)
profit = sales-cost
print(np.mean(profit), np.std(profit))
print(np.argmax(profit)+1)
print(np.where(profit==np.max(profit)))
print(np.argwhere(profit==np.max(profit)))

[5 7 6 8 8]
6.8 1.16619037896906
4
(array([3, 4], dtype=int64),)
[[3]
 [4]]
